stages:
  - lint
  - build
  - push

variables:
  ECR_REPO: "851725380821.dkr.ecr.ap-northeast-1.amazonaws.com/quantumcat"

# Golang-lint 檢查
lint:
  stage: lint
  image: golangci/golangci-lint:latest
  script:
    - golangci-lint run
  only:
    - main
    - dev
    - merge_requests

# 建構 Docker 映像
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache aws-cli       # 安裝 AWS CLI
    - aws sts get-caller-identity      # 檢查當前身份
    # - aws ecr describe-repositories    # 檢查倉庫訪問權限
    # - aws ecr get-authorization-token  # 檢查認證權限
    # - docker buildx create --use       # 設置 Docker Buildx
    # 登入 AWS ECR
    - ecr_credentials --region-id ${AWS_REGION} --assule-role-arn arn:aws:iam::REDACTED_AWS_ACCOUNT_DEMO:role/FatcatInternalRunnerAssumeRole | docker login --username AWS --password-stdin ${ECR_REPO}
  script:
    - docker buildx build
      --push
      --build-arg CI_COMMIT_SHA=${CI_COMMIT_SHA}
      -t ${ECR_REPO}/fatidentitycat:latest
      .
  only:
    - main
    - dev




