apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fatidentitycat.fullname" . }}-web
  labels:
    {{- include "fatidentitycat.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fatidentitycat.labels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "fatidentitycat.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/sealedsecret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Release.Namespace }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "fatidentitycat.app-image" . }}
          imagePullPolicy: Always
          args: ["./fat-identity-cat", "web"]
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          env:
            - name: TZ
              value: Asia/Taipei
          envFrom:
            - configMapRef:
                name: {{ include "fatidentitycat.fullname" . }}
            - secretRef:
                name: {{ include "fatidentitycat.fullname" . }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      restartPolicy: Always