{{- $encryptedData := dict }}
{{- /* 合併基礎加密配置 */ -}}
{{- if .Values.encryptedEnv }}
{{- $encryptedData = merge $encryptedData .Values.encryptedEnv }}
{{- end }}

{{- /* 根據環境載入額外的加密配置 */ -}}
{{- if eq .Values.global.environment "development" }}
{{- $demoValues := ($.Files.Get "values-demo.yaml" | fromYaml) }}
{{- if $demoValues.encryptedEnv }}
{{- $encryptedData = merge $encryptedData $demoValues.encryptedEnv }}
{{- end }}
{{- else if eq .Values.global.environment "production" }}
{{- $prodValues := ($.Files.Get "values-pro.yaml" | fromYaml) }}
{{- if $prodValues.encryptedEnv }}
{{- $encryptedData = merge $encryptedData $prodValues.encryptedEnv }}
{{- end }}
{{- end }}

{{- if $encryptedData }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "fatidentitycat.fullname" . }}
  labels:
    {{- include "fatidentitycat.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- toYaml $encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ include "fatidentitycat.fullname" . }}
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "fatidentitycat.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
