{{- if .Values.encryptedEnv }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "fatidentitycat.fullname" . }}
  labels:
    {{- include "fatidentitycat.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- with .Values.encryptedEnv }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      name: {{ include "fatidentitycat.fullname" . }}
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "fatidentitycat.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
