// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/hibiken/asynq"
	"github.com/jvdiamondtech/ms-identity-cat/internal/adapter/inbound/handler/api"
	"github.com/jvdiamondtech/ms-identity-cat/internal/adapter/inbound/handler/consumer"
	"github.com/jvdiamondtech/ms-identity-cat/internal/adapter/inbound/handler/worker"
	repository3 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/level"
	repository4 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/manager"
	"github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/merchant"
	repository2 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/player"
	repository5 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/tag"
	usecase5 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/level"
	usecase3 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/manager"
	"github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/merchant"
	usecase2 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/player"
	usecase4 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/tag"
	"github.com/jvdiamondtech/ms-identity-cat/internal/domain/ports/outbound/infrastructure"
	"github.com/jvdiamondtech/ms-identity-cat/internal/domain/ports/outbound/service"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/cache/redis"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/config"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/kds"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/queue"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/tracing"
	redis2 "github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeWebServer 初始化 Web 服務的 HTTP 處理器
func InitializeWebServer(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*api.HTTPHandler, error) {
	merchantRepository := repository.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := provideEventProducer(kdsService, logger)
	tracingService := provideTracingService()
	merchantUseCase := usecase.NewMerchantUseCase(merchantRepository, eventProducer, logger, tracingService)
	playerRepository := repository2.NewPlayerRepository(db)
	levelRepository := repository3.NewLevelRepository(db)
	client, err := provideRedisClient(redisManager)
	if err != nil {
		return nil, err
	}
	playerUseCase := usecase2.NewPlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger, client, tracingService)
	managerRepository := repository4.NewManagerRepository(db)
	managerUseCase := usecase3.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger, tracingService)
	httpHandler := api.NewHTTPHandler(merchantUseCase, playerUseCase, managerUseCase, logger)
	return httpHandler, nil
}

// InitializeWorkerServer 初始化 Worker 服務的處理器
func InitializeWorkerServer(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*worker.WorkerHandler, error) {
	merchantRepository := repository.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := provideEventProducer(kdsService, logger)
	tracingService := provideTracingService()
	merchantUseCase := usecase.NewMerchantUseCase(merchantRepository, eventProducer, logger, tracingService)
	playerRepository := repository2.NewPlayerRepository(db)
	levelRepository := repository3.NewLevelRepository(db)
	client, err := provideRedisClient(redisManager)
	if err != nil {
		return nil, err
	}
	playerUseCase := usecase2.NewPlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger, client, tracingService)
	managerRepository := repository4.NewManagerRepository(db)
	managerUseCase := usecase3.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger, tracingService)
	tagRepository := repository5.NewTagRepository(db)
	playerTagRepository := repository2.NewPlayerTagRepository(db)
	tagUseCase := usecase4.NewTagUseCase(tagRepository, merchantRepository, playerRepository, playerTagRepository, eventProducer, logger, tracingService, redisManager)
	playerLevelUseCase := usecase5.NewLevelUseCase(levelRepository, merchantRepository, eventProducer, logger, tracingService)
	workerHandler := worker.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, tagUseCase, playerLevelUseCase, logger)
	return workerHandler, nil
}

// InitializeWorkerComponents 初始化 Worker 服務的所有組件
func InitializeWorkerComponents(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager, db *gorm.DB) (*WorkerComponents, error) {
	merchantRepository := repository.NewMerchantRepository(db)
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	eventProducer := provideEventProducer(kdsService, logger)
	tracingService := provideTracingService()
	merchantUseCase := usecase.NewMerchantUseCase(merchantRepository, eventProducer, logger, tracingService)
	playerRepository := repository2.NewPlayerRepository(db)
	levelRepository := repository3.NewLevelRepository(db)
	client, err := provideRedisClient(redisManager)
	if err != nil {
		return nil, err
	}
	playerUseCase := usecase2.NewPlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger, client, tracingService)
	managerRepository := repository4.NewManagerRepository(db)
	managerUseCase := usecase3.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger, tracingService)
	tagRepository := repository5.NewTagRepository(db)
	playerTagRepository := repository2.NewPlayerTagRepository(db)
	tagUseCase := usecase4.NewTagUseCase(tagRepository, merchantRepository, playerRepository, playerTagRepository, eventProducer, logger, tracingService, redisManager)
	playerLevelUseCase := usecase5.NewLevelUseCase(levelRepository, merchantRepository, eventProducer, logger, tracingService)
	workerHandler := worker.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, tagUseCase, playerLevelUseCase, logger)
	server, err := provideWorkerServer(cfg, logger)
	if err != nil {
		return nil, err
	}
	workerComponents := &WorkerComponents{
		Handler: workerHandler,
		Server:  server,
	}
	return workerComponents, nil
}

// InitializeConsumerHandler 初始化 Consumer 服務的 Handler
func InitializeConsumerHandler(cfg *config.Config, logger infrastructure.Logger, redisManager *redis.Manager) (*consumer.ConsumerHandler, error) {
	queueService, err := queue.NewQueueService(cfg, logger)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger)
	if err != nil {
		return nil, err
	}
	consumerHandler := consumer.NewConsumerHandler(kdsService, queueService, logger)
	return consumerHandler, nil
}

// wire.go:

// WorkerComponents 包含 worker 所需的所有組件
type WorkerComponents struct {
	Handler *worker.WorkerHandler
	Server  *asynq.Server
}

var baseSet = wire.NewSet(queue.NewQueueService, provideRedisClient,
	provideTracingService, repository.NewMerchantRepository, repository2.NewPlayerRepository, repository4.NewManagerRepository, repository5.NewTagRepository, repository3.NewLevelRepository, repository2.NewPlayerTagRepository, provideEventProducer, usecase.NewMerchantUseCase, usecase2.NewPlayerUseCase, usecase3.NewManagerUseCase, usecase4.NewTagUseCase, usecase5.NewLevelUseCase,
)

// 事件生產者提供者
func provideEventProducer(kdsService *kds.KDSService, logger infrastructure.Logger) service.EventProducer {
	return kdsService
}

// TracingService提供者
func provideTracingService() infrastructure.TracingService {
	return tracing.NewService()
}

// 提供 worker 服務器
func provideWorkerServer(cfg *config.Config, logger infrastructure.Logger) (*asynq.Server, error) {
	return queue.NewWorkerServer(cfg, logger)
}

// 提供 Redis 客戶端
func provideRedisClient(manager *redis.Manager) (*redis2.Client, error) {
	redisInstance, err := manager.GetClient()
	if err != nil {
		return nil, err
	}
	return redisInstance, nil
}
