// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/hibiken/asynq"
	"github.com/jvdiamondtech/ms-identity-cat/internal/adapter/inbound/handler/api"
	"github.com/jvdiamondtech/ms-identity-cat/internal/adapter/inbound/handler/consumer"
	"github.com/jvdiamondtech/ms-identity-cat/internal/adapter/inbound/handler/worker"
	repository6 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/agent"
	repository7 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/failed_task_event"
	repository3 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/level"
	repository4 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/manager"
	"github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/merchant"
	repository2 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/player"
	repository5 "github.com/jvdiamondtech/ms-identity-cat/internal/adapter/outbound/repository/tag"
	usecase4 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/agent"
	usecase5 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/failed_task_event"
	usecase3 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/level"
	"github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/manager"
	usecase6 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/merchant"
	usecase7 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/player"
	usecase2 "github.com/jvdiamondtech/ms-identity-cat/internal/application/usecase/tag"
	"github.com/jvdiamondtech/ms-identity-cat/internal/domain/ports/inbound"
	"github.com/jvdiamondtech/ms-identity-cat/internal/domain/ports/outbound/infrastructure"
	repository8 "github.com/jvdiamondtech/ms-identity-cat/internal/domain/ports/outbound/repository"
	"github.com/jvdiamondtech/ms-identity-cat/internal/domain/ports/outbound/service"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/config"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/jwt"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/kds"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/queue"
	"github.com/jvdiamondtech/ms-identity-cat/internal/infrastructure/tracing"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeWebServer 初始化 Web 服務的 HTTP 處理器
func InitializeWebServer(cfg *config.Config, logger infrastructure.Logger, redisManager infrastructure.CacheManager, db *gorm.DB) (*api.HTTPHandler, error) {
	merchantRepository := repository.NewMerchantRepository(db)
	tracingService, err := provideTracingService(cfg)
	if err != nil {
		return nil, err
	}
	queueService, err := queue.NewQueueService(cfg, logger, tracingService)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger, tracingService)
	if err != nil {
		return nil, err
	}
	eventProducer := provideEventProducer(kdsService, logger)
	merchantUseCase := provideMerchantUseCase(merchantRepository, eventProducer, logger, tracingService, redisManager)
	playerRepository := repository2.NewPlayerRepository(db)
	levelRepository := repository3.NewLevelRepository(db)
	client, err := provideRedisClient(redisManager)
	if err != nil {
		return nil, err
	}
	jwtService := provideJWTService(cfg)
	playerUseCase := providePlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger, client, tracingService, redisManager, jwtService)
	managerRepository := repository4.NewManagerRepository(db)
	managerUseCase := usecase.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger, tracingService)
	httpHandler := api.NewHTTPHandler(merchantUseCase, playerUseCase, managerUseCase, logger, tracingService, eventProducer)
	return httpHandler, nil
}

// InitializeWorkerServer 初始化 Worker 服務的處理器
func InitializeWorkerServer(cfg *config.Config, logger infrastructure.Logger, redisManager infrastructure.CacheManager, db *gorm.DB) (*worker.WorkerHandler, error) {
	merchantRepository := repository.NewMerchantRepository(db)
	tracingService, err := provideTracingService(cfg)
	if err != nil {
		return nil, err
	}
	queueService, err := queue.NewQueueService(cfg, logger, tracingService)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger, tracingService)
	if err != nil {
		return nil, err
	}
	eventProducer := provideEventProducer(kdsService, logger)
	merchantUseCase := provideMerchantUseCase(merchantRepository, eventProducer, logger, tracingService, redisManager)
	playerRepository := repository2.NewPlayerRepository(db)
	levelRepository := repository3.NewLevelRepository(db)
	client, err := provideRedisClient(redisManager)
	if err != nil {
		return nil, err
	}
	jwtService := provideJWTService(cfg)
	playerUseCase := providePlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger, client, tracingService, redisManager, jwtService)
	managerRepository := repository4.NewManagerRepository(db)
	managerUseCase := usecase.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger, tracingService)
	tagRepository := repository5.NewTagRepository(db)
	playerTagRepository := repository2.NewPlayerTagRepository(db)
	tagUseCase := usecase2.NewTagUseCase(tagRepository, merchantRepository, playerRepository, playerTagRepository, eventProducer, logger, tracingService, redisManager)
	playerLevelUseCase := usecase3.NewLevelUseCase(levelRepository, merchantRepository, eventProducer, logger, tracingService)
	agentRepository := repository6.NewAgentRepository(db)
	agentUseCase := usecase4.NewAgentUseCase(agentRepository, merchantRepository, eventProducer, logger, tracingService)
	workerHandler := worker.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, tagUseCase, playerLevelUseCase, agentUseCase, logger, tracingService, queueService)
	return workerHandler, nil
}

// InitializeWorkerComponents 初始化 Worker 服務的所有組件
func InitializeWorkerComponents(cfg *config.Config, logger infrastructure.Logger, redisManager infrastructure.CacheManager, db *gorm.DB) (*WorkerComponents, error) {
	merchantRepository := repository.NewMerchantRepository(db)
	tracingService, err := provideTracingService(cfg)
	if err != nil {
		return nil, err
	}
	queueService, err := queue.NewQueueService(cfg, logger, tracingService)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger, tracingService)
	if err != nil {
		return nil, err
	}
	eventProducer := provideEventProducer(kdsService, logger)
	merchantUseCase := provideMerchantUseCase(merchantRepository, eventProducer, logger, tracingService, redisManager)
	playerRepository := repository2.NewPlayerRepository(db)
	levelRepository := repository3.NewLevelRepository(db)
	client, err := provideRedisClient(redisManager)
	if err != nil {
		return nil, err
	}
	jwtService := provideJWTService(cfg)
	playerUseCase := providePlayerUseCase(playerRepository, merchantRepository, levelRepository, eventProducer, logger, client, tracingService, redisManager, jwtService)
	managerRepository := repository4.NewManagerRepository(db)
	managerUseCase := usecase.NewManagerUseCase(managerRepository, merchantRepository, eventProducer, logger, tracingService)
	tagRepository := repository5.NewTagRepository(db)
	playerTagRepository := repository2.NewPlayerTagRepository(db)
	tagUseCase := usecase2.NewTagUseCase(tagRepository, merchantRepository, playerRepository, playerTagRepository, eventProducer, logger, tracingService, redisManager)
	playerLevelUseCase := usecase3.NewLevelUseCase(levelRepository, merchantRepository, eventProducer, logger, tracingService)
	agentRepository := repository6.NewAgentRepository(db)
	agentUseCase := usecase4.NewAgentUseCase(agentRepository, merchantRepository, eventProducer, logger, tracingService)
	workerHandler := worker.NewWorkerHandler(merchantUseCase, playerUseCase, managerUseCase, tagUseCase, playerLevelUseCase, agentUseCase, logger, tracingService, queueService)
	failedTaskEventRepository := repository7.NewFailedTaskEventRepository(db)
	failedTaskEventUseCase := usecase5.NewFailedTaskEventUseCase(failedTaskEventRepository, logger, tracingService)
	server, err := provideWorkerServer(cfg, logger, failedTaskEventUseCase, redisManager, tracingService)
	if err != nil {
		return nil, err
	}
	workerComponents := &WorkerComponents{
		Handler: workerHandler,
		Server:  server,
	}
	return workerComponents, nil
}

// InitializeConsumerHandler 初始化 Consumer 服務的 Handler
func InitializeConsumerHandler(cfg *config.Config, logger infrastructure.Logger, redisManager infrastructure.CacheManager) (*consumer.ConsumerHandler, error) {
	tracingService, err := provideTracingService(cfg)
	if err != nil {
		return nil, err
	}
	queueService, err := queue.NewQueueService(cfg, logger, tracingService)
	if err != nil {
		return nil, err
	}
	kdsService, err := kds.NewKDSService(cfg, queueService, redisManager, logger, tracingService)
	if err != nil {
		return nil, err
	}
	consumerHandler := consumer.NewConsumerHandler(kdsService, queueService, logger)
	return consumerHandler, nil
}

// wire.go:

// WorkerComponents 包含 worker 所需的所有組件
type WorkerComponents struct {
	Handler *worker.WorkerHandler
	Server  *asynq.Server
}

var baseSet = wire.NewSet(queue.NewQueueService, provideRedisClient,
	provideTracingService, repository.NewMerchantRepository, repository2.NewPlayerRepository, repository4.NewManagerRepository, repository5.NewTagRepository, repository3.NewLevelRepository, repository6.NewAgentRepository, repository7.NewFailedTaskEventRepository, repository2.NewPlayerTagRepository, provideEventProducer,
	provideJWTService,

	provideMerchantUseCase,
	providePlayerUseCase, usecase.NewManagerUseCase, usecase2.NewTagUseCase, usecase3.NewLevelUseCase, usecase4.NewAgentUseCase, usecase5.NewFailedTaskEventUseCase,
)

// 事件生產者提供者
func provideEventProducer(kdsService *kds.KDSService, logger infrastructure.Logger) service.EventProducer {
	return kdsService
}

// TracingService提供者
func provideTracingService(cfg *config.Config) (infrastructure.TracingService, error) {
	tracingService, err := tracing.NewTracingService(cfg)
	if err != nil {
		return nil, err
	}
	return tracingService, nil
}

// MerchantUseCase提供者（帶快取）
func provideMerchantUseCase(
	merchantRepo repository8.MerchantRepository,
	eventProducer service.EventProducer,
	logger infrastructure.Logger, tracing2 infrastructure.TracingService,

	cache infrastructure.CacheManager,
) inbound.MerchantUseCase {
	return usecase6.NewMerchantUseCase(merchantRepo, eventProducer, logger, tracing2, cache)
}

// JWT服務提供者
func provideJWTService(cfg *config.Config) service.JWTService {
	return jwt.NewJWTService(cfg.Auth.JWT.Secret, cfg.Auth.JWT.Issuer)
}

// PlayerUseCase提供者（帶快取）
func providePlayerUseCase(
	playerRepo repository8.PlayerRepository,
	merchantRepo repository8.MerchantRepository,
	levelRepo repository8.LevelRepository,
	eventProducer service.EventProducer,
	logger infrastructure.Logger, redis2 *redis.Client, tracing2 infrastructure.TracingService,

	cache infrastructure.CacheManager,
	jwtService service.JWTService,
) inbound.PlayerUseCase {
	return usecase7.NewPlayerUseCase(playerRepo, merchantRepo, levelRepo, eventProducer, logger, redis2, tracing2, cache, jwtService)
}

// 提供 worker 服務器
func provideWorkerServer(cfg *config.Config, logger infrastructure.Logger, failedTaskUseCase inbound.FailedTaskEventUseCase, redisManager infrastructure.CacheManager, tracing2 infrastructure.TracingService) (*asynq.Server, error) {
	return queue.NewWorkerServer(cfg, logger, failedTaskUseCase, redisManager, tracing2)
}

// 提供 Redis 客戶端
func provideRedisClient(manager infrastructure.CacheManager) (*redis.Client, error) {
	redisInstance, err := manager.GetClient()
	if err != nil {
		return nil, err
	}
	return redisInstance, nil
}
