# Global settings
global:
  environment: development

env:
  # 應用程序設置
  APP_NAME: "fat-identity-cat"
  APP_ENV: "development"
  APP_PORT: "8080"
  APP_DEBUG: "true"

  # HTTP Server 設置
  SERVER_HTTP_DOMAIN: ""
  SERVER_READ_TIMEOUT: "30s"
  SERVER_WRITE_TIMEOUT: "30s"
  SERVER_IDLE_TIMEOUT: "120s"

# Application settings
app:
  name: fatidentitycat
  appName: fatidentitycat
  image:
    repository: REDACTED_AWS_ACCOUNT_DEMO.dkr.ecr.ap-northeast-1.amazonaws.com/quantumcat/fatidentitycat
    tag: latest
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 64Mi
